postgres:
  build: postgres
  ports:
    - "5432:5432"
  volumes:
    - "/home/core/data:/var/lib/postgresql/data"
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
datomicdb:
  build: transactor
  ports:
    - "4334:4334"
  links:
    - postgres
    - waiter
  volumes:
    - "/home/core/share/transactor/data:/data"
waiter:
  image: aanand/wait
  links:
    - postgres
console:
  build: datomic-console
  ports:
    - "9000:9000"
  links:
    - waiter
    - datomicdb
    - postgres
devapp:
  build: app
  ports:
    - "35001:35001"
    - "8000:8000"
    - "5005:5005"
    - "3449:3449"
  volumes:
    - "/home/core/share/app:/usr/src/app"
  environment:
    - DATOMIC_USER
    - DATOMIC_PASSWORD
    - DATOMIC_CONNECT_URL=datomic:sql://people?jdbc:postgresql://postgres:5432/datomic?user=datomic&password=datomic
    - JIRA_USERNAME
    - JIRA_PASSWORD
  links:
    - waiter
    - datomicdb
    - postgres

